assetic:
    assets:
        vendors:
            inputs:
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/json2.js'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/jquery.min.js'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/underscore.min.js'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/backbone.min.js'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/*'
        plugins:
            inputs:
                - '@RuianTwitterBootstrapBundle/Resources/public/js/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/plugins/*'
        app:
            inputs:
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/application.js'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/core/model/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/core/collection/base.js'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/core/collection/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/core/helper/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/core/views/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/activity/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/service/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/customer/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/project/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/timeslice/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/user/*'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/main.js'
                - '@DimeTimetrackerFrontendBundle/Resources/public/js/app/router.js'
