assetic:
    filters:
        lessphp:
            file: "%kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php"
            apply_to: "\.less$"
    assets:
        css_vendors:
            inputs:
                #- "bundles/phpugltwitterbootstrap/css/bootstrap.css"
                - "bundles/dimetimetrackerfrontend/css/foundation.min.css"
                - "bundles/dimetimetrackerfrontend/css/normalize.css"
        css_plugins:
            inputs:
                - "bundles/dimetimetrackerfrontend/css/bootstrap-datepicker.css"
        css_app:
            inputs:
                - "bundles/dimetimetrackerfrontend/css/dime.css"
                - "bundles/dimetimetrackerfrontend/css/tracking.css"
                - "bundles/dimetimetrackerfrontend/css/print.css"

        js_vendors:
            inputs:
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/jquery.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/jquery.cookie.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.abide.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.accordion.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.alert.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.clearing.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.dropdown.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.equalizer.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.interchange.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.joyride.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.magellan.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.offcanvas.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.orbit.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.reveal.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.tab.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.tooltip.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/foundation.topbar.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/angular.min.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/http-auth-interceptor.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/json2.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/modernizr.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/placeholder.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/vendors/*"
        js_plugins:
            inputs:
                - "@BazingaExposeTranslationBundle/Resources/public/js/translator.min.js"
        js_app:
            inputs:
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/application.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/app/index.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/app/activity.js"
                - "@DimeTimetrackerFrontendBundle/Resources/public/js/app/tracking.js"

