DimeTimetrackerFrontendBundle:
    resource: "@DimeTimetrackerFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
